name: build

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release tag"
        required: false
        default: ""
      release_notes:
        description: "Release notes"
        required: false
        default: ""
  push:
    branches:
      - "**"

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: build
        run: g++ -O2 -std=c++17 -o gdinstaller main.cpp

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gdinstaller-linux-x86_64
          path: gdinstaller

      - name: Create tag and release
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.release_tag != '' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.release_tag }}
          name: ${{ inputs.release_tag }}
          body: ${{ inputs.release_notes }}
          files: gdinstaller
          generate_release_notes: false
